version: '3.8'

services:
  init:
    build:
      context: ./init
      dockerfile: Dockerfile
    container_name: myapp_init
    image: myapp_init
    env_file: ".env"
    depends_on:
      - db
    networks:
      - mynetwork

  app:
    build:
      context: ./llm_app
      dockerfile: Dockerfile
    container_name: llm_app
    image: llm_app
    env_file: ".env"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "1337:1337"
    depends_on:
      - init
    networks:
      - mynetwork

  db:
    image: postgres:13.3
    container_name: myapp_db
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  mynetwork: